<?php

namespace App\Http\Controllers;

use Auth;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use DB;
use App\Models\Document;
use App\Models\DocumentType;
use App\Models\Office;
use Illuminate\Http\Request;
use App\Models\TrackingRecord;

class DocumentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:sanctum');
    }

    public function getDocumentTypes(): Collection
    {
        return DocumentType::get();
    }

    public function getOfficeList(): Collection
    {
        return Office::get();
    }

    // TODO: Validation, logging and error message
    public function addNewDocument(Request $request)
    {
        DB::beginTransaction();
        try {
            $document = new Document;
            $document->tracking_code = $request->tracking_id;
            $document->title = strtoupper($request->document_title);
            $document->is_external = $request->is_external;
            $document->document_type_id = $request->document_type;
            $document->originating_office_id = $request->originating_office_id;
            $document->external_office_name = $request->external_office_name;
            $document->current_office_id = Auth::user()->office->id;
            $document->sender_name = $request->sender_name;
            $document->page_count = $request->page_count;
            $document->date_filed = Carbon::createFromFormat('Y-m-d H:i', $request->date_filed.' '.$request->time_filed);
            $document->is_terminal = false;
            $document->remarks = $request->remarks;
            $document->attachment_page_count = $request->attachment_page_count;
            $document->save();

            $datetime = Carbon::now();
            $tracking_record = new TrackingRecord;
            $tracking_record->document_id = $document->id;
            $tracking_record->actions = 10;
            $tracking_record->status = 20;
            $tracking_record->touched_by = Auth::user()->id;
            $tracking_record->last_touched = Carbon::createFromFormat('Y-m-d H:i', $request->date_filed.' '.$request->time_filed);
            $tracking_record->remarks = 'generated by document creation';
            $tracking_record->save();

        } catch(ValidationException $error) {
            DB::rollback();
            throw $error;
        } catch(\Exception $error) {
            DB::rollback();
            throw $error;
        }
        DB::commit();
        return 'Successfully added document with tracking number : '.$document->tracking_code;
    }
}
